# Generated by Django 4.2.2 on 2023-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
                ("foods", models.ManyToManyField(to="menus.food")),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="items",
            field=models.ManyToManyField(to="menus.item"),
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
                ("facebook", models.URLField(max_length=100)),
                ("instagram", models.URLField(max_length=100)),
                ("menus", models.ManyToManyField(to="menus.menu")),
            ],
        ),
    ]
