# Generated by Django 4.2.2 on 2023-06-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="qr_code",
        ),
        migrations.AddField(
            model_name="business",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
        migrations.RemoveField(
            model_name="business",
            name="menus",
        ),
        migrations.AddField(
            model_name="business",
            name="menus",
            field=models.OneToOneField(
                default="", on_delete=django.db.models.deletion.PROTECT, to="menus.menu"
            ),
        ),
    ]
