# Generated by Django 4.2.2 on 2023-06-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_remove_menu_qr_code_business_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="menus",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="menus.menu"
            ),
        ),
    ]
